stages:
    ingest:
        cmd: 
        - ImageCrawler.py data/raw/ data/images/
        deps: 
        -  data/raw/
        -  data/images/
        outs:
        - data/images/*.png
            cache: false

    preprocess: # Images, Long Lat, Text Data, Other Features

