stages:
    ingest: Params file possible
        cmd: 
        - ./src/ingest/ImageCrawler.py data/raw/ train.csv /root/data/images/
        -  data/raw/
        -  data/images/ 
        outs:
        - data/images/*.png
            cache: false

    preprocess: # Images, Long Lat, Text Data, Other Features

