# Mini Pipeline with dvc
stages:
    merge:
        cmd:
        - ./src/features/selection/merge.py data/interim data/canonical
        deps:
        -  data/interim/reviews/csv/reviews.csv
        -  data/interim/train/train.csv 
        -  data/interim/train/amenities.csv
        -  data/interim/train/images.jsonl
        -  data/interim/test/test.csv 
        -  data/interim/test/amenities.csv
        -  data/interim/test/images.jsonl
    predict:
        cmd: 
        - ./src/models/predict.py 0FEMC4VA5U  # any listing_id in test data possible
        deps:
        - data/models/xgb_reg.pkl    
        - data/canonical/test/test.csv
     